from turtle import Turtle, Screen

arch = Turtle()

arch.penup()
arch.goto(-200, -50)
arch.pendown()
arch.pencolor("dodgerblue3")
arch.fillcolor("dodgerblue3")
arch.begin_fill()
arch.left(70)
arch.forward(200)
arch.right(90)
arch.forward(50)
arch.left(170)
arch.forward(50)
arch.right(80)
arch.forward(100)

arch.right(130)
arch.forward(200)
arch.right(90)
arch.forward(50)
arch.left(170)
arch.forward(50)
arch.right(80)
arch.forward(120)
arch.right(140)
arch.forward(120)
arch.right(75)
arch.circle(35, 191)
arch.right(68)
arch.forward(100)
arch.end_fill()
arch.hideturtle()
arch.penup()

arch.setx(-175.0)
arch.sety(-85.0)
arch.pencolor("dodgerblue3")
arch.write("Arch", font=("Arial", 30, "bold"))

arch.setx(-58.0)
arch.sety(-85.0)
arch.pencolor("black")
arch.write("Linux", font=("Arial", 30, "bold"))


screen = Screen()
screen.exitonclick()
